


#definicion de la bdd
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=josegaray
quarkus.datasource.password=5404822

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/db_araf_V2
quarkus.datasource.jdbc.max-size=16